package berlin.vs.u2mailbox;

import javax.swing.*;
import java.awt.*;

public class ChatWindow extends javax.swing.JFrame {

    private JTextArea chatArea;
    private JLabel lblInfo;
    private JScrollPane scrollPane;
    private JPanel panel;


    /** Creates new form ChatWindow */
    public ChatWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //                           
    private void initComponents() {

        panel = new JPanel();
        panel.setLayout(new BorderLayout());

        lblInfo = new JLabel();
        scrollPane = new JScrollPane();
        chatArea = new JTextArea();


        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(300, 300);
        setTitle("Message Box");

        lblInfo.setText("Messages:");
        chatArea.setColumns(20);
        chatArea.setRows(5);
        scrollPane.setViewportView(chatArea);

        panel.add(lblInfo,BorderLayout.PAGE_START);
        panel.add(chatArea,BorderLayout.CENTER);
        add(panel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }

    /**
     * @return the chatArea
     */
    public javax.swing.JTextArea getjTextArea1() {
        return chatArea;
    }

    /**
     * @param chatArea the chatArea to set
     */
    public void setjTextArea1(javax.swing.JTextArea jTextArea1) {
        this.chatArea = jTextArea1;
    }
}
